<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Register</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>556fc28e-4d67-4b26-b145-288d0660c52d</testSuiteGuid>
   <testCaseLink>
      <guid>93e5ce8b-843d-4ed6-97ca-8c947dec2b14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Case Register</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>aa9f9c3f-ca6c-456e-bb9f-c20e6c3aca1d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DT_Register</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>aa9f9c3f-ca6c-456e-bb9f-c20e6c3aca1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>firstName</value>
         <variableId>f8773cb8-0206-426c-bd81-ced4f6c68b6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>aa9f9c3f-ca6c-456e-bb9f-c20e6c3aca1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastName</value>
         <variableId>1edcd2a3-b559-4f20-acaf-0385bb7a344c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>aa9f9c3f-ca6c-456e-bb9f-c20e6c3aca1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>0f46f51a-2b83-4e16-aefd-ae981a3557b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>aa9f9c3f-ca6c-456e-bb9f-c20e6c3aca1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>d7cb25da-4369-470a-bfe8-a490e3e705f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>aa9f9c3f-ca6c-456e-bb9f-c20e6c3aca1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>companyName</value>
         <variableId>502f3b67-0835-4b57-8689-3097c5c80bd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>aa9f9c3f-ca6c-456e-bb9f-c20e6c3aca1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>phoneNumber</value>
         <variableId>d9338c35-c36e-4ccf-99a9-c436cf8d767d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>aa9f9c3f-ca6c-456e-bb9f-c20e6c3aca1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>stateProvince</value>
         <variableId>ee2dcd9d-b27d-4cdc-8f6e-ad78d1f90c63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>aa9f9c3f-ca6c-456e-bb9f-c20e6c3aca1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>paymentService</value>
         <variableId>bbffa6ed-4411-4f9b-ac00-178dbe091ee7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
